clone:
  git:
    image: plugins/git
    depth: 1

pipeline:
  check-app-compatbility:
    image: nextcloudci/php7.1:php7.1-16
    environment:
      - APP_NAME=impersonate
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation
      - cd apps/$APP_NAME/
    when:
      matrix:
        TESTS: check-app-compatbility
  signed-off-check:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=impersonate
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server
      - php ./build/signed-off-checker.php
    when:
      matrix:
        TESTS: signed-off-check
  php5.6:
    image: nextcloudci/php5.6:php5.6-3
    environment:
      - APP_NAME=impersonate
      - CORE_BRANCH=stable12
      - DB=sqlite
    commands:
      - apt update && apt-get -y install php5-xdebug

      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml

      # Create coverage report
      - wget https://codecov.io/bash -O codecov.sh
      - sh -c "if [ '$DRONE_BUILD_EVENT' = 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -P $DRONE_PULL_REQUEST -t f3e5390a-15fe-46ea-9e10-8b24addb0d40 -f clover.xml; fi"
      - sh -c "if [ '$DRONE_BUILD_EVENT' != 'pull_request' ]; then bash codecov.sh -B $DRONE_BRANCH -C $DRONE_COMMIT -t f3e5390a-15fe-46ea-9e10-8b24addb0d40 -f clover.xml; fi"
    when:
      matrix:
        TESTS: php5.6
  php7.0:
    image: nextcloudci/php7.0:php7.0-2
    environment:
      - APP_NAME=impersonate
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml
    when:
      matrix:
        TESTS: php7.0
  php7.1:
    image: nextcloudci/php7.1:php7.1-3
    environment:
      - APP_NAME=impersonate
      - CORE_BRANCH=master
      - DB=sqlite
    commands:
      # FIXME: Move into Docker image
      - yum -y install wget

      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME

      # Run phpunit tests
      - cd tests/unit/
      - phpunit --configuration phpunit.xml
    when:
      matrix:
        TESTS: php7.1

matrix:
  include:
    - TESTS: php5.6
    - TESTS: php7.0
    - TESTS: php7.1
    - TESTS: check-app-compatbility
    - TESTS: signed-off-check

